class CustomError(Exception):
    """Пользовательское исключение."""

    pass
